---
version: '3'

includes:
  codeqa:
    taskfile: ./taskfiles/Taskfile_codequality.yml
    dir: ./taskfiles

  build:
    taskfile: ./taskfiles/Taskfile_gobuild.yml
    dir: ./taskfiles

  test:
    taskfile: ./taskfiles/Taskfile_gotest.yml
    dir: ./taskfiles

tasks:
  build:fast:
    desc: ensure go build works for all modules
    cmds:
      - task: gobuild:go:build

  build:clean:
    desc: ensure go build works for all modules
    cmds:
      - task: gobuild:go:build

  format:
    desc: formats the code correctly
    cmds:
      - task: codequality:format 

  lint:
    desc: lints the go code
    cmds:
      - task: codequality:lint 

  go:modules:
    desc: tidies the go modules
    cmds: 
      - task: codequality:modules

  test:unit:
    desc: run the unit tests
    cmds:
      - task: gotest:go:unit

  # test:integration:
  #   desc: run the azurite integration tests
  #   cmds:
  #    - task: azurite:preflight
  #    - task: gotest:go:azurite
